### ISSUE TITLE
NETS2022 Database

### ISSUE THREAD

**Issue by stfran22** [Drexel-UHC/NETS#18]
**Purpose** \
Document NETS2022 Database Creation
List changes from NETS2019 database

**Progress**

- [x] Address table 
- [x] BG_CC_TC_Xwalk
- [x] BusinessInfo 
- [x] Category Descriptions
- [x] ClassifiedLong
- [x] DunsLocations
- [x] DunsMove
- [x] Tract-Level Measures
- [x] ZCTA-Level Measures

**Comment by stfran22** [comment]
@jannettim trying to add the Address table to the db and I encounter this error four times, which results in the table missing four records:

`SQLState = 22001, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation`.

I checked max lengths for each value in all of the columns and none exceed what we've set in the schema. Any ideas?

**Comment by stfran22** [comment]
no, I'm not sure how I would find that out other than exporting all the records that made it in and comparing. I can do that if its the best option.

**Comment by jannettim** [comment]
I think the easiest thing to do would be to read the address file into python, select the inserted AddressIDs from the database, and then compare those two lists.

I should be able to do that today. Because I think the easiest way around this is to just manually insert the 4 rows and see what happens.

Alternatively, the bcp should export out an error file if you haven't run a bcp since the address table import, that file should have the missed rows in it. The filepath for the export file should be in the bcp command.

**Comment by jannettim** [comment]
Oh, I just checked and it seems like I misunderstood. Since you said that there were 4 rows missing, I thought that the Address table was already loaded minus those 4 rows. But it looks like there is no data in the table. Could you send me the full bcp command?

**Comment by stfran22** [comment]
Ah no you understood correctly, I had just deleted the table so I could try other flags in the command. I have it uploading as we speak. It only takes a few minutes so I'll check the error file when it's done and keep you updated.

**Comment by stfran22** [comment]
I'm assuming this is an encoding situation? All but four uploaded again.
error file contents: 
```
#@ Row 15721401, Column 2: String data, right truncation @#
A015721400	RT 3 BOX 176 C ���������������	SAINT STEPHENS	AL	36569	<NULL>
#@ Row 16935901, Column 2: String data, right truncation @#
A016935900	�����������������������������	EAST TALLASSEE	AL	36023	<NULL>
#@ Row 18613800, Column 2: String data, right truncation @#
A018613799	STAR RT 54 �������������������	PINE HILL	AL	36769	<NULL>
#@ Row 18971335, Column 2: String data, right truncation @#
A018971334	GENERAL DELIVERY �������������	HAMPTON	AR	71744	9999
```

**Comment by jannettim** [comment]
Yeah that looks like an encoding issue, let me take a look and see if I can get them inserted

**Comment by jannettim** [comment]
As discussed via chat, there was an original UnicodeDecodeError in the original code that was replacing a non-unicode character with a series of other characters. This encoding error can be fixed by reading the file as latin-1 instead of utf-8.

I tried reading the original file and output lines that had the decode error by decoding them with the latin-1 codec. I read through the output and tried to identify the correct values for the above data. It looks like, the offending character is some form of non-breaking space, which means that the data should read:

|AddressID|GcAddress|GcCity|GcState|GcZIP|GcZIP4|Original Raw File ID|
|----------|-----------|-------|--------|------|--------|-------------------|
|A015721400|RT 3 BOX 176 C|SAINT   STEPHENS|AL|36569||114296296|
|A016935900||EAST TALLASSEE|AL|36023||128654076*|
|A018613799|STAR RT 54|PINE   HILL|AL|36769||163373681|
|A018971334|GENERAL   DELIVERY|HAMPTON|AR|71744|9999|168892701|

*This value could also be from item 128819075

@stfran22 I attached the original ID from the company file if you wanted to look at this and check. But if you are OK with these values, I suggest we just manually insert them now.

**Comment by stfran22** [comment]
@jannettim by original ID do you mean DunsNumber? This looks good to me I think we can just go ahead and insert manually. I'll take care of it.

**Comment by stfran22** [comment]
successfully added four missing records. record count of address table in db matches that of input file.

**Comment by stfran22** [comment]
@jannettim ran out of space uploading the second to last file into the db. I'd say there's about 6gb left in the partially-loaded file, then the last file will likely be about 8gb. Maybe add another 25gb to include overhead?

**Comment by jannettim** [comment]
Sure thing. But wait a sec. So, you saw the email from Kari right about the fixes to the data? from walls and associates. Just to double check the dnb rating was not used in your processing so its fine to continue uploading?

**Comment by stfran22** [comment]
Yup not an issue. Thanks for looking out

**Comment by jannettim** [comment]
OK, great, I increased the size of the database to 120 GB

**Comment by stfran22** [comment]
@sjmelly I guess we're adding the zcta level measures to the database as well? This may require additional space but I'll try without increasing first if we want it there.

**Comment by stfran22** [comment]
@jannettim do you foresee any issues with a table with over 500 columns? The tract-level and zcta-level tables both have 512.

**Comment by jannettim** [comment]
The maximum number of columns is 1,024. So it should technically be possible. But from a design perspective that might warrant a check to see if we should break that up. Are all those columns measuring similar things that can't be split into more than one table?

**Comment by stfran22** [comment]
We could split them in half: half are counts and half are densities. We'd then have 257 each.

**Comment by stfran22** [comment]
@jannettim I'm going to make four new tables in the db, one each for tract/zcta-level counts/densities. I don't have unique primary keys for these, as they are unique only by tract/zcta id and year. Should I add a new integer ID column for each of them as the primary key? Or just use the current two columns as a primary? 

I've added all of the necessary columns in [the create tables sql file](https://github.com/Drexel-UHC/NETS/blob/main/database/Code/create_tables.sql) - if you could just add the necessary PK/constraint stuff that would be awesome.

**Comment by stfran22** [comment]
Nope, we don't need any additional tract or zcta data.

**Comment by jannettim** [comment]
OK, so if we aren't connecting to any other tables, I presume you might want to join the tract counts and densities together (the the same with the zcta tables). This is a little odd because neither table necessarily will list all possible tracts (or zctas). So while I would want to put s foreign key there, the missing tract/zcta table makes that difficult. So I think I'm going to recommend something like this


```SQL
CREATE TABLE Tracts (
        Tract10Id                       INTEGER PRIMARY KEY IDENTITY,
        Tract10                          VARCHAR(11) NOT NULL
)

CREATE TABLE ZCTA (
        ZCTA10Id                       INTEGER PRIMARY KEY IDENTITY,
        ZCTA10                          VARCHAR(5) NOT NULL
)


CREATE TABLE TractDensities (
	
        Tract10Id                          INTEGER PRIMARY KEY
	/* REST OF THE COLUMNS EXCEPT FOR Tract10 */

       CONSTRAINT FQ_TractDensities_Tracts_Tract10Id FOREIGN KEY (Tract10Id) REFERENCES Tracts (Tract10Id)

CREATE TABLE ZCTADensities (
         ZCTA10Id                         INTEGER PRIMARY KEY,
	/* REST OF THE COLUMNS EXCEPT FOR ZCTA10 */

       CONSTRAINT FQ_ZCTADensities_ZCTA_ZCTA0Id FOREIGN KEY (ZCTA0Id) REFERENCES ZCTA (ZCTA0Id)
```

I think the extra tables are worth it for a couple of reasons. First, it makes the database structure make more sense. Second, we don't have to repeat the tract/zcta codes across tables. Third, it will make it easier to keep the IDs consistent across tables.

I think we should create the Tract and ZCTA tables, load it in with the unique tract and ZCTA names, which will create the IDs. Then write script to replace the Tract10 value in the tables with the ID number and upload them. If that makes sense to you I can edit the SQL script tomorrow.

Also, last question for now, for the constraints on the data columns (containing the actual counts and densities) is there ever a reason why data for a tract would be missing?

**Comment by jannettim** [comment]
After talking with @stfran22 we are going to go with this structure.

```SQL
CREATE TABLE Tracts (
        /* CONTAIN UNIQUE 11 DIGIT TRACT NAMES */
        Tract10Id                       INTEGER PRIMARY KEY,
        Tract10                          VARCHAR(11) NOT NULL
)

CREATE TABLE ZCTA (
        /* UNIQUE 5 DIGIT ZCTA NAMES */
        ZCTA10Id                       INTEGER PRIMARY KEY,
        ZCTA10                          VARCHAR(5) NOT NULL
)

CREATE TABLE TractCounts (
	
        TractYearId                        INTEGER PRIMARY KEY,
        Tract10Id                          INTEGER NOT NULL,
	/* REST OF THE COLUMNS EXCEPT FOR Tract10 */

       CONSTRAINT FQ_TractCounts_Tracts_Tract10Id FOREIGN KEY (Tract10Id) REFERENCES Tracts (Tract10Id)

CREATE TABLE TractDensities (
	
        TractYearId                        INTEGER PRIMARY KEY,
        Tract10Id                          INTEGER NOT NULL,
	/* REST OF THE COLUMNS EXCEPT FOR Tract10 */

       CONSTRAINT FQ_TractDensities_Tracts_Tract10Id FOREIGN KEY (Tract10Id) REFERENCES Tracts (Tract10Id),
       CONSTRAINT FQ_TractCounts_Tracts_TractYearId FOREIGN KEY (TractYearId) REFERENCES TractCounts (TractYearId)
```

And the counts and density data should have a NOT NULL constraint.

**Comment by sjmelly** [comment]
@stfran22 Does the table Tracts have any records in it?
When I run the query
select top (10) *  
FROM dbo.Tracts
I get 0 rows

**Comment by stfran22** [comment]
@sjmelly try again. Just uploaded. Finishing the NETS2022 metadata doc now. I'll let you know where I put it on the server in a comment later today.

**Comment by sjmelly** [comment]
@stfran22 It works as I expected now.

**Comment by stfran22** [comment]
Database is fully populated. Metadata document is located at Z:\UHC_Data\NETS_UHC\NETS2022\Documentation\NETS2022_metadata20240109.docx. Going to close this as completed, but I anticipate creating an issue regarding improving performance in the future.
