### ISSUE TITLE
BEDDN Info Sheet

### ISSUE THREAD

**Issue by stfran22** [Drexel-UHC/NETS#26]
We will create an info sheet to introduce researchers to the Business Establishment Data Derived from NETS.

**Comment by stfran22** [comment]
@sjmelly @kam642 I saved a [draft](https://github.com/Drexel-UHC/NETS/files/14172572/BEDDN_InfoSheet20240201.docx) of the info sheet at:

\\files.drexel.edu\colleges\SOPH\Shared\UHC\ResearchAndData\UHC_Data\NETS_UHC\ForDataPortal\

I have a comment and other highlighted portions that I just wanted eyes on. Let me know if there are any sections missing or edits to make.

**Comment by stfran22** [comment]
@sjmelly @kam642 I saved a [draft](https://github.com/Drexel-UHC/NETS/files/14172572/BEDDN_InfoSheet20240201.docx) of the info sheet at:

\\files.drexel.edu\colleges\SOPH\Shared\UHC\ResearchAndData\UHC_Data\NETS_UHC\ForDataPortal\

I have a comment and other highlighted portions that I just wanted eyes on. Let me know if there are any sections missing or edits to make.

**Comment by kam642** [comment]
@stfran22 @sjmelly I made some edits and added comments in the version on the server with my initials on the end.
BEDDN_InfoSheet20240201SM_KM.docx.

**Comment by kam642** [comment]
@stfran22 @sjmelly Can you make sure that there is something in this doc about cautioning against adding categories together due to duplicates? I think I forgot to check if that was included in here.

Also, make sure the file formats are included in here if necessary. Just curious, is there a reason the establishment level is not in a spatial format? Don't you need that to calculate things for MESA? Could we just save that and could be made available to others somehow?
